[package]
name = "byd"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18"
wgpu = "0.12"
winit = { version = "0.26" }
log = "0.4"
env_logger = "0.9"
futures = "0.3.15"
downcast-rs = "1.2.0"
mutunga = { path = "../mutunga" }

[build-dependencies]
glob = "0.3"
shaderc = "0.7"
